model : "weights/dsr_large_sample_epoch=20.ckpt"
test_path : data/original/test/normal2
test_output_path : output/test/normal
training_path : data/original/train/normal
training_output_path : output/training
checkpoint_path : checkpoints
epochs : 60
batch_size : 6
learning_rate : 0.0001
threshold : 0.99995
alpha : 0.7
image_size : 512